### Finding the correct lat/lon for ORCA_025 (calculating transport)

In [1]:
from glob import glob
import numpy as np
import xarray as xr
import pandas as pd

import warnings
warnings.simplefilter('ignore')
%config InlineBackend.print_figure_kwargs = {'bbox_inches': None}

In [2]:
orc_m05 = xr.open_dataset('/scratch/usr/shklvn09/NUDATA/ORCA/05-data/meshmask/mesh_mask.nc')
orc_m025 = xr.open_dataset('/scratch/usr/shklvn09/NUDATA/ORCA/025-data/meshmask/mesh_mask.nc')

### Assigning coordinates to the variables

In [3]:
orc_m025.coords['x'] = ('x',orc_m025.nav_lon.values[0,:])
orc_m025.coords['y'] = ('y',orc_m025.nav_lat.values[:,0])

In [4]:
orc_m05.coords['x'] = ('x',orc_m05.nav_lon.values[0,:])
orc_m05.coords['y'] = ('y',orc_m05.nav_lat.values[:,0])

In [5]:
orc_m025

<xarray.Dataset>
Dimensions:       (t: 1, x: 1442, y: 1021, z: 46)
Coordinates:
  * x             (x) float32 72.75 73.0 73.25 73.5 ... 72.25 72.5 72.75 73.0
  * y             (y) float32 -77.010475 -76.95416 -76.89761 ... 50.0 49.995502
Dimensions without coordinates: t, z
Data variables:
    nav_lon       (y, x) float32 72.75 73.0 73.25 ... 73.00568 73.000015 73.0
    nav_lat       (y, x) float32 -77.010475 -77.010475 ... 49.995502 49.995502
    nav_lev       (z) float32 ...
    time_counter  (t) float64 ...
    tmask         (t, z, y, x) int8 ...
    umask         (t, z, y, x) int8 ...
    vmask         (t, z, y, x) int8 ...
    fmask         (t, z, y, x) int8 ...
    tmaskutil     (t, y, x) int8 ...
    umaskutil     (t, y, x) int8 ...
    vmaskutil     (t, y, x) int8 ...
    fmaskutil     (t, y, x) int8 ...
    glamt         (t, y, x) float32 ...
    glamu         (t, y, x) float32 ...
    glamv         (t, y, x) float32 ...
    glamf         (t, y, x) float32 ...
    gphit         (t, y, x) float32 ...
    gphiu         (t, y, x) float32 ...
    gphiv         (t, y, x) float32 ...
    gphif         (t, y, x) float32 ...
    e1t           (t, y, x) float64 ...
    e1u           (t, y, x) float64 ...
    e1v           (t, y, x) float64 ...
    e1f           (t, y, x) float64 ...
    e2t           (t, y, x) float64 ...
    e2u           (t, y, x) float64 ...
    e2v           (t, y, x) float64 ...
    e2f           (t, y, x) float64 ...
    ff            (t, y, x) float64 ...
    mbathy        (t, y, x) int16 ...
    misf          (t, y, x) int16 ...
    isfdraft      (t, y, x) float32 ...
    e3t_0         (t, z, y, x) float64 ...
    e3u_0         (t, z, y, x) float64 ...
    e3v_0         (t, z, y, x) float64 ...
    e3w_0         (t, z, y, x) float64 ...
    gdept_0       (t, z, y, x) float32 ...
    gdepu         (t, z, y, x) float32 ...
    gdepv         (t, z, y, x) float32 ...
    gdepw_0       (t, z, y, x) float32 ...
    gdept_1d      (t, z) float64 ...
    gdepw_1d      (t, z) float64 ...
    e3t_1d        (t, z) float64 ...
    e3w_1d        (t, z) float64 ...

In [6]:
lat_05 = orc_m05.nav_lat
lon_05 = orc_m05.nav_lon

In [7]:
lat_025 = orc_m025.nav_lat
lon_025 = orc_m025.nav_lon

In [ ]:
lat_05

### Lat/Lon needed for Drake Passage

In [9]:
lat_05[65:118,438] # (from 66 until 188 em bash) 

<xarray.DataArray 'nav_lat' (y: 53)>
array([-67.29768 , -67.103935, -66.90862 , -66.71173 , -66.51326 , -66.313194,
       -66.11152 , -65.90823 , -65.703316, -65.496765, -65.28857 , -65.07871 ,
       -64.867195, -64.65399 , -64.4391  , -64.22252 , -64.00423 , -63.78421 ,
       -63.56247 , -63.338985, -63.113754, -62.88676 , -62.658   , -62.42746 ,
       -62.195126, -61.960995, -61.725048, -61.487286, -61.247692, -61.00626 ,
       -60.762974, -60.517834, -60.27082 , -60.021927, -59.77115 , -59.51847 ,
       -59.263885, -59.00738 , -58.748955, -58.48859 , -58.226284, -57.96202 ,
       -57.695797, -57.427605, -57.15743 , -56.88527 , -56.61111 , -56.334946,
       -56.05677 , -55.776573, -55.494347, -55.210083, -54.923775],
      dtype=float32)
Coordinates:
    x        float32 -68.25
  * y        (y) float32 -67.29768 -67.103935 ... -55.210083 -54.923775

In [11]:
lat_05[117,438] #last latitude

<xarray.DataArray 'nav_lat' ()>
array(-54.923775, dtype=float32)
Coordinates:
    x        float32 -68.25
    y        float32 -54.923775

In [15]:
lon_05[65:118,437]

<xarray.DataArray 'nav_lon' (y: 53)>
array([-68.75, -68.75, -68.75, -68.75, -68.75, -68.75, -68.75, -68.75, -68.75,
       -68.75, -68.75, -68.75, -68.75, -68.75, -68.75, -68.75, -68.75, -68.75,
       -68.75, -68.75, -68.75, -68.75, -68.75, -68.75, -68.75, -68.75, -68.75,
       -68.75, -68.75, -68.75, -68.75, -68.75, -68.75, -68.75, -68.75, -68.75,
       -68.75, -68.75, -68.75, -68.75, -68.75, -68.75, -68.75, -68.75, -68.75,
       -68.75, -68.75, -68.75, -68.75, -68.75, -68.75, -68.75, -68.75],
      dtype=float32)
Coordinates:
    x        float32 -68.75
  * y        (y) float32 -67.29768 -67.103935 ... -55.210083 -54.923775

### Just confirming 

In [20]:
a = np.where((lat_05 > -67.3) & (lat_05 < -54.92))

In [21]:
a[0]

array([ 65,  65,  65, ..., 117, 117, 117])

In [16]:
b = np.where((lon_05 == -68.75))

In [17]:
b[1][0]

437

### Getting same lat/lon for ORCA 025

In [22]:
c = np.where((lat_025 > -67.3) & (lat_025 < -54.92))

In [23]:
c[0]

array([130, 130, 130, ..., 234, 234, 234])

In [18]:
d = np.where((lon_025 == -68.75))

In [19]:
d[1][0]

874

In [24]:
lat_025[130:235,874] #python [0:5] from that element (0) till 4th, so indices 132 and 236

<xarray.DataArray 'nav_lat' (y: 105)>
array([-67.29768 , -67.201004, -67.103935, -67.00648 , -66.90862 , -66.81037 ,
       -66.71173 , -66.61269 , -66.51326 , -66.41343 , -66.313194, -66.212555,
       -66.11152 , -66.01008 , -65.90823 , -65.80598 , -65.703316, -65.60025 ,
       -65.496765, -65.392876, -65.28857 , -65.18385 , -65.07871 , -64.97316 ,
       -64.867195, -64.7608  , -64.65399 , -64.54676 , -64.4391  , -64.331024,
       -64.22252 , -64.11359 , -64.00423 , -63.894436, -63.78421 , -63.673557,
       -63.56247 , -63.450947, -63.338985, -63.22659 , -63.113754, -63.00048 ,
       -62.88676 , -62.772602, -62.658   , -62.542953, -62.42746 , -62.311516,
       -62.195126, -62.078285, -61.960995, -61.84325 , -61.725048, -61.606396,
       -61.487286, -61.367718, -61.247692, -61.127205, -61.00626 , -60.88485 ,
       -60.762974, -60.640636, -60.517834, -60.39456 , -60.27082 , -60.14661 ,
       -60.021927, -59.896774, -59.77115 , -59.645046, -59.51847 , -59.391415,
       -59.263885, -59.13587 , -59.00738 , -58.87841 , -58.748955, -58.619015,
       -58.48859 , -58.35768 , -58.226284, -58.094395, -57.96202 , -57.829155,
       -57.695797, -57.561947, -57.427605, -57.292767, -57.15743 , -57.0216  ,
       -56.88527 , -56.74844 , -56.61111 , -56.473278, -56.334946, -56.19611 ,
       -56.05677 , -55.916924, -55.776573, -55.635715, -55.494347, -55.35247 ,
       -55.210083, -55.067184, -54.923775], dtype=float32)
Coordinates:
    x        float32 -68.75
  * y        (y) float32 -67.29768 -67.201004 ... -55.067184 -54.923775

In [26]:
lat_025[236,876]

<xarray.DataArray 'nav_lat' ()>
array(-54.635414, dtype=float32)
Coordinates:
    x        float32 -68.25
    y        float32 -54.635414

### Finding longitudes for Ross Sea

In [5]:
lon_05

<xarray.DataArray 'nav_lon' (y: 511, x: 722)>
array([[72.75    , 73.25    , 73.75    , ..., 72.25    , 72.75    , 73.25    ],
       [72.75    , 73.25    , 73.75    , ..., 72.25    , 72.75    , 73.25    ],
       [72.75    , 73.25    , 73.75    , ..., 72.25    , 72.75    , 73.25    ],
       ...,
       [72.99536 , 73.00464 , 73.03129 , ..., 72.96871 , 72.99536 , 73.00464 ],
       [72.999985, 73.000015, 73.00986 , ..., 72.99014 , 72.999985, 73.000015],
       [73.000015, 72.999985, 72.99014 , ..., 73.00986 , 73.000015, 72.999985]],
      dtype=float32)
Coordinates:
  * x        (x) float32 72.75 73.25 73.75 74.25 ... 71.75 72.25 72.75 73.25
  * y        (y) float32 -77.010475 -76.89761 -76.78378 ... 49.995502 49.995502

In [6]:
d = np.where(lon_05[1] < -150)

In [7]:
d

(array([215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227,
        228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240,
        241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253,
        254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266,
        267, 268, 269, 270, 271, 272, 273, 274]),)

In [8]:
e = np.where(lon_05[1] > 170)

In [9]:
e

(array([195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207,
        208, 209, 210, 211, 212, 213, 214]),)

In [10]:
print(lon_05[1,195:275])

<xarray.DataArray 'nav_lon' (x: 80)>
array([ 170.25,  170.75,  171.25,  171.75,  172.25,  172.75,  173.25,  173.75,
        174.25,  174.75,  175.25,  175.75,  176.25,  176.75,  177.25,  177.75,
        178.25,  178.75,  179.25,  179.75, -179.75, -179.25, -178.75, -178.25,
       -177.75, -177.25, -176.75, -176.25, -175.75, -175.25, -174.75, -174.25,
       -173.75, -173.25, -172.75, -172.25, -171.75, -171.25, -170.75, -170.25,
       -169.75, -169.25, -168.75, -168.25, -167.75, -167.25, -166.75, -166.25,
       -165.75, -165.25, -164.75, -164.25, -163.75, -163.25, -162.75, -162.25,
       -161.75, -161.25, -160.75, -160.25, -159.75, -159.25, -158.75, -158.25,
       -157.75, -157.25, -156.75, -156.25, -155.75, -155.25, -154.75, -154.25,
       -153.75, -153.25, -152.75, -152.25, -151.75, -151.25, -150.75, -150.25],
      dtype=float32)
Coordinates:
  * x        (x) float32 170.25 170.75 171.25 171.75 ... -151.25 -150.75 -150.25
    y        float32 -76.89761


In [21]:
print(lon_05[1,274])

<xarray.DataArray 'nav_lon' ()>
array(-150.25, dtype=float32)
Coordinates:
    x        float32 -150.25
    y        float32 -76.89761


In [13]:
print(lon_05[1,720:])

<xarray.DataArray 'nav_lon' (x: 2)>
array([72.75, 73.25], dtype=float32)
Coordinates:
  * x        (x) float32 72.75 73.25
    y        float32 -76.89761


In [144]:
lon_05[1,275]

<xarray.DataArray 'nav_lon' ()>
array(-149.75, dtype=float32)
Coordinates:
    x        float32 -149.75
    y        float32 -76.89761